### ISSUE TITLE
Generated code for `toNullable Nothing` produces `undefined`?

### ISSUE THREAD

**Issue by Javran** [paf31/purescript-nullable#4] opened 2015-07-24 19:41 UTC
It works fine from psci, but when I try to use it from js side, I find `toNullable Nothing` produces `undefined` instead of `null`.

To reproduce:

```bash
$ psc --version
0.7.1.0
$ pulp init && pulp dep install purescript-nullable && pulp build
$ psc-bundle output/**/*.js -m Data.Nullable >test.js
$ echo "module.exports = PS;" >> test.js
$ node 
> var PS = require("./test");
undefined
> PS["Data.Nullable"].toNullable( PS["Data.Maybe"].Nothing.value );
undefined
```

**Comment by hdgarrood** [comment] 2015-12-11 02:25
I think this was fixed by https://github.com/paf31/purescript-nullable/commit/57966bfacc905122a0e8ebecd031fac5a2303ae2. I can't reproduce it now.

**Comment by paf31** [comment] 2015-12-11 18:48
Right, thanks.

**Closed by paf31** 2015-12-11 18:48 UTC
